# Generated by Django 2.2.28 on 2023-02-01 00:51

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter ingredient name",
                        max_length=200,
                        verbose_name="Ingredient name",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        help_text="Enter measurement unit of ingredient",
                        max_length=200,
                        verbose_name="Measurement unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient",
                "verbose_name_plural": "ingredients",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter recipe name",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveSmallIntegerField(
                        help_text="Enter cooking time in minutes (at least 1 min)",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                "Cooking time cannot be less than one minute.",
                            )
                        ],
                        verbose_name="Cooking time",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Enter description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Add recipe image",
                        upload_to="recipes/images/",
                        verbose_name="Recipe image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredients",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        help_text="Enter amount of ingredient",
                        verbose_name="Amount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter tag",
                        max_length=200,
                        unique=True,
                        verbose_name="Tag",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Enter color in HEX format",
                        max_length=7,
                        unique=True,
                        validators=[
                            recipes.validators.validate_hex_format_color
                        ],
                        verbose_name="Color in HEX format",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Enter tag URL (slug)",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                        verbose_name="Tag URL (slug)",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="recipes.Recipe",
                    ),
                ),
            ],
        ),
    ]
