# Generated by Django 2.2.28 on 2023-02-02 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20230201_0351"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("recipe__name",),
                "verbose_name": "favorites",
                "verbose_name_plural": "favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("name",),
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ("id",),
                "verbose_name": "shopping cart",
                "verbose_name_plural": "shopping carts",
            },
        ),
        migrations.AlterField(
            model_name="recipeingredients",
            name="amount",
            field=models.PositiveSmallIntegerField(
                help_text="Enter amount of ingredient",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Amount cannot be less than one piece."
                    )
                ],
                verbose_name="Amount",
            ),
        ),
    ]
