# Generated by Django 2.2.28 on 2023-02-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20230209_0554"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Enter tag URL (slug)",
                max_length=200,
                unique=True,
                verbose_name="tag URL (slug)",
            ),
        ),
    ]
