# Generated by Django 2.2.28 on 2023-02-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20230210_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredients",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.Ingredient",
            ),
        ),
    ]
