# Generated by Django 2.2.28 on 2023-02-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_auto_20230210_1432"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeIngredients",
            new_name="RecipeIngredient",
        ),
    ]
