# Generated by Django 2.2.28 on 2023-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20230208_1921"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscription",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="subscriber",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique_subscription"
            ),
        ),
    ]
